strt/base/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright 2019, GeoSolutions SAS.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# APIs imports
from strt_geoportale import urls as geoportale_urls
from serapide_core import urls as serapide_core_urls

# Dajngo admin
urlpatterns = [
    path('admin/', admin.site.urls),
]

# Apps urls
urlpatterns += [
    path('', include('strt_portal.urls')),
    path('users/', include('strt_users.urls'))
]

# APIs urls
urlpatterns += [
    path('', include(serapide_core_urls)),
]

# Geoportale urls
urlpatterns += [
    path('geoportale/', include(geoportale_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

strt/strt_tests/forms.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright 2019, GeoSolutions SAS.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django import forms
from django.core.validators import RegexValidator

from strt_users.models import (
    Ente,
    # MembershipType
)


class ChoiceFieldNoValidation(forms.ChoiceField):

    def validate(self, value):
        pass


class UserAuthenticationForm(forms.Form):

    fiscal_code = forms.CharField(
        label='Codice Fiscale',
        required=True,
        validators=[
            RegexValidator(
                regex='^(?i)(?:(?:[B-DF-HJ-NP-TV-Z]|[AEIOU])[AEIOU][AEIOUX]|'
                      '[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}[\dLMNP-V]{2}(?:[A-EHLMPR-T]'
                      '(?:[04LQ][1-9MNP-V]|[1256LMRS][\dLMNP-V])|[DHPS][37PT][0L]|'
                      '[ACELMRT][37PT][01LM])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L]'
                      '(?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$',
                message='Codice fiscale errato.',
            ),
        ]
    )
    organizations = forms.ModelChoiceField(
        label='Enti',
        queryset=Ente.objects.all(),
        required=False
    )

    membership_type = ChoiceFieldNoValidation(
        label='Ruolo',
        required=True,
    )

    hidden_orgs = forms.CharField(
        widget=forms.HiddenInput(),
        required=False
    )

strt/strt_tests/templates/strt_tests/user_authentication_test.html
<!--

Copyright 2019, GeoSolutions SAS.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.

-->


{% extends "base.html" %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{{ block.super }} - {% trans 'test autenticazione utente'|capfirst %}{% endblock head_title %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'strt_users/css/users.css' %}"/>
{% endblock styles %}

{% block content %}

    <div class="bg-light h-100 py-5 m-0 px-6">

        <h2>{% trans 'test autenticazione utente'|capfirst %}</h2>
        <hr class="border-warning border-bottom"></hr>

        <p>La procedura di autenticazione:</p>
        <ol>
            <li>
                <p>
                    Codice Fiscale
                    <br>
                    <small>
                        Inserire il Codice Fiscale associato all'utenza; deve essere registrato e valido.
                    </small>
                </p>
            </li>
            <li>
                <p>
                    Ente
                    <br>
                    <small>
                        Selezionare l'Ente al quale si vuole accedere dalla lista; l'utenza deve avere accesso all'Ente con un Ruolo valido.
                    </small>
                </p>
            </li>
            <li>
                <p>
                    Ruolo
                    <br>
                    <small>
                        Selezionare il Ruolo dalla lista; il ruolo deve essere stato attivato per l'Ente selezionato.
                    </small>
                </p>
            </li>
        </ol>

        <form method="POST" novalidate id="user-membership" class="col-12 col-lg-12"
            membership-type-data-url="{% url 'membership_type_data' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-secondary my-2 my-lg-4"
                   value="{% trans 'autentica'|capfirst %}">
        </form>
        <span class="text-danger" id="orgs-errors"></span>

    </div>

{% endblock content %}

{% block add_script %}

    <script>

        $('#id_organizations').change(function () {

            var type_select = $('#id_membership_type');

            type_select.empty();
            type_select.append('<option value="" selected="">---------</option>')

            var url = $('#user-membership').attr('membership-type-data-url');
            var user_id = $('#id_fiscal_code').val();
            var org_id = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'user_id': user_id,
                    'selected_org': org_id
                },
                dataType: 'json',
                success: function (data) {
                    data.forEach( function(m_type) {
                            $('#id_membership_type').append(
                                '<option value="'
                                    .concat(m_type.code)
                                    .concat('">')
                                    .concat(m_type.description)
                                    .concat('</option>')
                            );
                        }
                    );
                    $('#id_membership_type').attr('disabled', false);
                }
            });
        });

        $("#user-membership").submit(function() {
            $('#orgs-errors').text('');
            var org = $('#id_organizations option:selected');
            if (org.val()) {
                var orgs = $('input[name="hidden_orgs"]').val();
                $('input[name="hidden_orgs"]').val(org.val());
                var li = $('<li/>').text(org.text())
                    .on("click", function() {
                        $(this).remove();
                        $('#orgs-errors').text('');
                    });
                $('#orgs').prepend(
                    li.addClass('btn border border-secondary m-1')
                );
                $('#id_organizations')[0].selectedIndex = 0;
            } else {
                $('input[name="hidden_orgs"]').val('');
                $('#orgs-errors').text('Valori inseriti non validi');
            }
        });
    </script>

{% endblock add_script %}